name: fourth wf

on: 
    workflow_dispatch:
    push:
        branches:
            - main
            - 'feature/*'


jobs:
   code-coverage:
        name: Coverage

        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup node
              uses: actions/setup-node@v4
              with:
                node-version: 20
            
            - name: install npm
              run: npm install

            - name: unit testing
              continue-on-error: true
              run: npm run coverage
            
            - uses: actions/upload-artifact@v4
              if: failure() || success()
              with:
                name: code-coverage-result
                path: coverage
                retention-days: 5